version: '3.7'

services:
    tss-api-dev:
        image: registry.gitlab.com/trus1/api/dev
        container_name: tss-api-dev
        environment:
            NODE_ENV: ${NODE_ENV}
            PORT: ${PORT}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
            JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
            JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
            ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
            SENDGRID_API_KEY: ${SENDGRID_API_KEY}
            SENDGRID_EMAIL: ${SENDGRID_EMAIL}
            SENT_EMAIL_FROM: ${SENT_EMAIL_FROM}
            PINDO_API_KEY: ${PINDO_API_KEY}
            PINDO_API_URL: ${PINDO_API_URL}
            API_URL: ${API_URL}
            CLIENT_APP_URL: ${CLIENT_APP_URL}
            ADMIN_APP_URL: ${ADMIN_APP_URL}
            DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
            CRON_EXPRESSION: ${CRON_EXPRESSION}
            SWAGGER_ENABLED: ${SWAGGER_ENABLED}
        depends_on:
            - tss-psqldb-dev
        ports:
            - 8072:5000
        restart: unless-stopped
        networks:
            - tss-backend-dev-net

    tss-psqldb-dev:
        image: postgres:14-alpine
        container_name: tss-psqldb-dev
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - tss-psqldb-dev:/var/lib/postgresql/data
        networks:
            - tss-backend-dev-net
            # - tss-postgres-net-dev
volumes:
    tss-psqldb-dev:
    # tss-pgadmin-data-dev:
networks:
    tss-backend-dev-net:
    # tss-postgres-net-dev:
