version: '3.7'

services:
    tss-api-prod:
        image: registry.gitlab.com/trus1/api/main
        container_name: tss-api-prod
        environment:
            NODE_ENV: ${NODE_ENV}
            PORT: ${PORT}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
            JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
            JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
            ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
            SENDGRID_API_KEY: ${SENDGRID_API_KEY}
            SENDGRID_EMAIL: ${SENDGRID_EMAIL}
            SENT_EMAIL_FROM: ${SENT_EMAIL_FROM}
            PINDO_API_KEY: ${PINDO_API_KEY}
            PINDO_API_URL: ${PINDO_API_URL}
            API_URL: ${API_URL}
            CLIENT_APP_URL: ${CLIENT_APP_URL}
            ADMIN_APP_URL: ${ADMIN_APP_URL}
            DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
            CRON_EXPRESSION: ${CRON_EXPRESSION}
            SWAGGER_ENABLED: ${SWAGGER_ENABLED}
        depends_on:
            - tss-psqldb-prod
        ports:
            - 8010:5000
        restart: unless-stopped
        networks:
            - tss-backend-prod-net

    tss-psqldb-prod:
        image: postgres:14-alpine
        container_name: tss-psqldb-prod
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - tss-psqldb-prod:/var/lib/postgresql/data
        networks:
            - tss-backend-prod-net
            - tss-postgres-net-prod
            # - tss-postgres-net-prod
    tss-pgadmin-prod:
        image: dpage/pgadmin4:6.12
        container_name: tss-pgadmin-prod
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: 80
        depends_on:
            - tss-psqldb-prod
        ports:
            - ${PGADMIN_PORT}:80
        volumes:
            - tss-pgadmin-data-prod:/var/lib/pgadmin
        restart: unless-stopped
        networks:
            - tss-postgres-net-prod
volumes:
    tss-psqldb-prod:
        external: true
    tss-pgadmin-data-prod:
        external: true
networks:
    tss-backend-prod-net:
    tss-postgres-net-prod:
