export enum EApplicationStatus {
    APPROVED = 'APPROVED',
    DENIED = 'DENIED',
    FIRST_STAGE_PASSED = 'FIRST_STAGE_PASSED',
    PENDING = 'PENDING',
    SUBMITTED = 'SUBMITTED',
}

export enum EAnswerStatus {
    ACCEPTED = 'ACCEPTED',
    REJECTED = 'REJECTED',
    FURTHER_INFO_REQUIRED = 'FURTHER_INFO_REQUIRED',
    NONE = 'NONE',
}

export enum EPlatform {
    WEBSITE = 'WEBSITE',
    WHATSAPP = 'WHATSAPP',
    INSTAGRAM = 'INSTAGRAM',
}
